- .travis.yml
- mocket/mocket.py
- tests/test_http.py
- tests/test_mocket.py
implement shutdown method on mocked sockets
add a testcase which leads to the usage of socket shutdown
> add shutdown method

- mocket/mocket.py
- tests/test_redis.py
- true redis tests not actually running under mocketize
- multiple connect error, make true redis work under mocketize for more than one single command, avoid reconnecting on error after every operation
- buffer seek error
> fix a gazillion problems

- .gitignore
- README.rst
- mocket/__init__.py
- mocket/mocket.py
- tests/test_mocket.py
Reverts mocketize/python-mocket#32
> Revert "Aligning code to the current master branch"

- mocket/mocket.py
- mocket/mockhttp.py
- tests/test_https.py
> Adding SSL support.

- mocket/mocket.py
- mocket/mockhttp.py
- tests/tests35/test_http_aiohttp.py
> Body sent via send() is not considered

- .travis.yml
- mocket/mocket.py
- requirements.txt
Thanks to the @jmcbailey patch at https://github.com/gabrielfalcao/HTTPretty/issues/242.
> Fix for #65

- tests/tests35/test_http_asks_curio.py
- tests/tests35/test_http_asks_trio.py
Adding currently failing tests using [asks](https://github.com/theelous3/asks) and [curio](https://github.com/dabeaz/curio)/[trio](https://github.com/python-trio/trio).
Can be a good reference for improvement in that direction if desired.
> WIP : adding tests for asks running with trio or curio. currently failing.

- Pipfile
- Pipfile.lock
- mocket/mocket.py
- setup.py
I hope I covered all the cases. We should probably add this to the build matrix somehow.
No additional tests were added. I can add them if required.
Fixes #80.
> Switch to xxhash when possible

- mocket/mocket.py
- tests/main/test_mocket.py
Added has requests like httpretty, sometimes you just want to check that the url that you've patched has been called
> Added has_requests

- mocket/mocket.py
> Partial wildcards fix

- README.rst
- conftest.py
- mocket/mockhttp.py
- mocket/plugins/httpretty/__init__.py
- pytest.ini
- setup.cfg
- tests/main/test_httpretty.py
> Refactoring HTTPretty mock

- .isort.cfg
- .pre-commit-config.yaml
- README.rst
- mocket/__init__.py
- mocket/mocket.py
- mocket/mockhttp.py
- mocket/plugins/httpretty/__init__.py
- tests/main/test_http.py
Mocket now support `urequests` (https://pypi.org/project/urequests/)
Thanks to @amotl for the perfect explanation at #111 and the related test at https://gist.github.com/amotl/015ef6b336db55128798d7f1a9a67dea.
> Multiple HTTP writes

- Pipfile
- README.rst
- mocket/__init__.py
- mocket/mocket.py
- tests/main/test_http.py
- tests/main/test_mocket.py
As reported by @KyleKing in #128.
Fix for #130.
> Fix for `.makefile()`

- Makefile
- Pipfile
- mocket/__init__.py
- setup.py
I honestly prefer my solution so I'll close the other PR while being thankful to @brycedrennan for underlining the problem with its PR #132.
> Fix for new version of `pip`

- mocket/__init__.py
- mocket/mocket.py
- tests/main/test_mocket.py
> Use MocketSocket as context manager

- mocket/async_mocket.py
- mocket/mocket.py
- mocket/plugins/httpretty/__init__.py
> Patch from PR #150 (Refactored the mocketize decorator)

- mocket/mocket.py
- tests/main/test_mocket.py
> Change request_cls to prevent unintended bytes -> str conversion

- mocket/mocket.py
- tests/main/test_mocket.py
>  MocketEntry.request_class str vs bytes 

- .github/workflows/main.yml
- README.rst
- mocket/async_mocket.py
- mocket/mocket.py
- mocket/mockhttp.py
- mocket/plugins/httpretty/__init__.py
- mocket/utils.py
- tests/main/test_mode.py
Thanks to @ento for their amazing contributions.
Fix for #218.
> Add allowed locations (whitelist) for STRICT mode

- pyproject.toml
- tests/test_mocket.py
> Pinning the version of `aiohttp`

- pyproject.toml
> Better conf for `pytest-asyncio`
