mindflayer/python-mocket

mocket/compat.py, mocket/mocket.py, mocket/mockhttp.py, mocket/mockredis.py, requirements.txt, setup.py, tests/main/test_http.py, tests/main/test_mocket.py, tests/main/tests.main.test_http.TrueHttpEntryTestCase.test_truesendall_with_dump_from_recording.json
Use _select.select_ to support chunked responses.
=> Custom encoding and fix for chunked responses

mocket/mocket.py, tests/main/test_mocket.py
When subsequent payload to be pushed by mocket was shorter than previous one, additional data were dumped. This was because BytesIO object had longer length; calling truncate() on the BytesIO object solves this problem
code to reproduce the problem, before this patch:
```
@mocketize
def test_something():
Mocket.register(
MocketEntry(
('example.com', 80),
[
b'this is some long payload'
b'short',
]
),
)
```
then, when one would use socket object, and call `recv` on it, one would get part of the first payload with the second call
=> Add missing truncate() call on BytesIO object

mocket/mockhttp.py
There were some HTTP methods missing, so it would be nice to define them here.
I also alphabetically sorted the variables.
=> Add missing HTTP methods to mockhttp

mocket/mocket.py
We encountered an issue where HTTPS calls after tests using mocket were failing because the original SSL objects were not being correctly restored. Swapping those keys around should fix that.
**Verification**:
I ran the following snippet:
```
In [1]: import mocket
In [2]: mocket.Mocket.enable()
In [3]: mocket.Mocket.disable()
In [4]: import requests
In [5]: requests.get('https://google.com')
```
Before this fix, it threw `TypeError: __init__() got an unexpected keyword argument 'sock'`. After, I got the requests Response object I expected.
=> Swap SSL objects restored after mocket is disabled

.travis.yml, Makefile, mocket/mocket.py, runtests.py, test_requirements.txt, tests/main/test_mocket.py
Adding `recv_into` socket function as requested by #71
=> Adding `recv_into` support

mocket/__init__.py, mocket/mockhttp.py, tests/main/test_http.py
`Mocket` won't fail if `magic` cannot be imported, as requested by #81.
=> Avoid libmagic importerror

mocket/mocket.py
=> TypeError: __init__() takes from 1 to 4 positional arguments but 5 were given

setup.py
I wasn't able to install due to unicode characters in readme
Error:
```
Collecting mocket==2.7.2 (from -r requirements.txt (line 44))
Downloading https://files.pythonhosted.org/packages/a5/c9/478da224865ede99a69cee4bcd7593185d8a92e5aa6f044e86445cfe7ab8/mocket-2.7.2.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-a52nwr9c/mocket/setup.py", line 37, in <module>
long_description=io.open('README.rst').read(),
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 25: ordinal not in range(128)
```
=> fixes non ascii characters in README.rst

Makefile, mocket/__init__.py, mocket/compat.py, tests/main/test_http.py
=> POST-ing binary files was failing

mocket/mocket.py, tests/main/test_mocket.py
Per Python 3 [documentation](https://docs.python.org/3.5/library/socket.html#socket.socket.recv_into), the second parameter of `recv_into` is optional.
=> Fix compliance with original recv_into()

MANIFEST.in, setup.py
Exclude tests.* from the wheel, but include tests/ in the sdist
Fixes https://github.com/mindflayer/python-mocket/issues/100
=> Add tests to sdist

mocket/__init__.py, mocket/compat.py, mocket/mocket.py
Fix for removing `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc'`.
=> Fix for removing DeprecationWarning

mocket/mockhttp.py
file's builtin magic module has a somewhat different API, and it's not
co-installable with pypi:python-magic as both has the same name. Adding
a fallback logic here makes mocket work with either one.
All related tests are passing here.
=> Add support for file's builtin magic module

setup.py
pipenv should not be required for sdist installations.
noticed this behavior when reviewing https://github.com/NixOS/nixpkgs/pull/95689
=> Remove pipenv from `setup_requires`

Makefile, Pipfile, mocket/__init__.py, mocket/mockhttp.py, tests/main/test_http.py
I also took the chance for replacing the HTTP parser and refactoring `Request`.
Fix for #123.
=> Fix for managing multiple `sendall()` correctly

Pipfile, mocket/__init__.py, tests/main/test_mocket.py
At least until [this](https://github.com/micheles/decorator/issues/126) is resolved.
Fix for #148.
=> Avoid `decorator>=5` as dependency

mocket/mocket.py, mocket/utils.py
=> Mock `check_hostname` everywhere

mocket/__init__.py, mocket/mocket.py, mocket/mockhttp.py, tests/main/test_http.py
Attempt to fix #158. But first, make it fail.
=> Multi `register()`

Pipfile, mocket/__init__.py, mocket/mocket.py, tests/tests37/test_httpx.py
=> Support for calls made by `fastapi`

.github/workflows/main.yml, mocket/__init__.py, mocket/mocket.py
=> Fix for an unconvential usage of Mocket

.github/workflows/main.yml
Dear Giorgio,
this is another improvement to the CI configuration, in order to optimize resource usage. The patch is stacked on top of your commits from #192. I hope you like it.
With kind regards,
Andreas.
=> Improve efficiency on CI

mocket/mocket.py, pyproject.toml, tests/main/test_mocket.py, tests/tests38/test_http_aiohttp.py, tests/tests38/test_http_httpx.py
This PR attempts to fix a few issues:
In a project I'm working with, a mocketized test would fail if it ran after a test that makes a real HTTPS request. Both use aiohttp. Clearing [aiohttp's internal cache](https://github.com/aio-libs/aiohttp/blob/v3.9.1/aiohttp/connector.py#L915-L917) that holds an SSLContext object fixed the issue.
I encountered more issues while trying to write a PR for the above:
* Saw that I get a 'too many open files' error when I was experimenting with running the same test many times through parameterization.
* Fixed by returning existing `Mocket.r_fd` from `MocketSocket.fileno` if it's already set and closing the pipe's file descriptors when resetting Mocket
* Testing HTTPS test cases that use aiohttp with Python 3.11 just wouldn't pass - same error as  #209
* I …
=> Fixes for allowing making a mixture of unmocked and mocked HTTPS requests using aiohttp

mocket/mocket.py, pyproject.toml, tests/main/test_mocket.py, tests/tests38/test_http_aiohttp.py, tests/tests38/test_http_httpx.py
Thanks to @ento for his amazing contribution!
=> External contribution

tests/tests38/test_http_aiohttp.py
=> Adding testcase for proving #209 was fixed

mocket/mocket.py, tests/main/test_mocket.py
Fixes #221
The issue was caused by how `Mocket._address` was used to determine which host and port to connect to in `MocketSocket.true_sendall`. `Mocket._address` gets overwritten when another `MocketSocket` instance's `connect` method gets called and could be the wrong address to use in that case.
This PR fixes the issue by referencing the current instance's `_host` and `_port` attributes instead.
I see that, in `MocketSocket.getpeercert`, there's code that accounts for the case where `_host` and `_port` are not set to truthy values; not sure if that can happen in `true_sendall` as well and should be accounted for, or if the current simple fix will be enough (or maybe even that it'd be a different kind of bug if `_host` and `_port` aren't set by the time `true_sendall` gets called).
=> When creating true socket connection, use host and port stored in instance variables, not in the Mocket class's variable

README.rst, mocket/async_mocket.py, mocket/mocket.py, mocket/mockhttp.py, mocket/utils.py, tests/main/test_mode.py
I'm trying to use a library that sends test stats to a remote server in the background, and tests that use Mocket in strict mode would fail intermittently when the library tries to make an HTTP request.
This PR adds a new `strict_mode_allowed: list[str | tuple[str, int]]` parameter to `Mocketizer`, which specifies which host or host and port can be made requests against even in strict mode.
Suggestions for a better name for the parameter would be welcome, if any. What some other libraries use...
- [HTTPretty's unmerged PR](https://github.com/gabrielfalcao/HTTPretty/pull/448/files): `whitelist`
- [WebMock, a Ruby library](https://github.com/bblimke/webmock#external-requests-can-be-disabled-while-allowing-specific-requests): `allow`
=> Allow specifying strict mode exceptions

mocket/mocket.py, tests/main/test_socket.py
=> Add getblocking() method

mocket/mocket.py, mocket/mockhttp.py, mocket/utils.py, tests/main/test_asyncio.py
I managed to fix #237 and make it work for all the use-cases.
=> Fix regression

mocket/mockhttp.py, pyproject.toml
Better having a pure Python HTTP parser.
=> Replacing `httptools` with `h11`

mocket/__init__.py, mocket/compat.py, mocket/mockhttp.py, pyproject.toml, tests/test_compat.py, tests/test_http.py
Fix for #254 by switching to a pure-Python implementation.
=> Switching to using `puremagic` for identifying MIME types

mocket/__init__.py, mocket/mocket.py, mocket/plugins/aiohttp_connector.py, tests/test_asyncio.py
This in a small tool to make things work when Mocket gets stuck during testing with `aiohttp`.
Kinda fix for #247.
=> `aiohttp` reuses SSLContext instances created at import-time

Makefile
👋 I'm using mocket from inside pyodide and pyodide requires ["pure python wheels"](https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package) to be able to install a given package. 
I saw that mocket currently publishes only an sdist and not a pure python wheel, so making this PR to add a pure python wheel as well.
I tested out the change and it seems to work:
```
@wilhelmklopp ➜ /workspaces/python-mocket (build-pure-python-wheel) $ uv run python3 -m build --sdist --wheel .
* Creating isolated environment: virtualenv+pip...
* Installing packages in isolated environment:
- hatchling>=1.22.2
* Getting build dependencies for sdist...
* Building sdist...
* Creating isolated environment: virtualenv+pip...
* Installing packages in isolated …
```
=> Build and publish pure python wheel

mocket/entry.py, mocket/inject.py, mocket/io.py, mocket/mocket.py, mocket/mocketizer.py, mocket/mode.py, mocket/plugins/httpretty/__init__.py, mocket/socket.py, mocket/types.py, tests/test_socket.py
continuation of #261 and #263
This PR does two things:
- move the enable- and disable-logic into a dedicated file
- introduce a state-object to replace the singleton-class
This is done to prevent cyclic-imports.
=> Refactor: introduce state object

mocket/__init__.py, mocket/inject.py, mocket/io.py, mocket/plugins/aiohttp_connector.py, mocket/socket.py, mocket/ssl/context.py, mocket/utils.py
this PR renames some classes while re-exporting the old names for backwards-compat.
- `MocketSocketCore` -> `MocketSocketIO`
- `FakeSSLContext` -> `MocketSSLContext`
- `SuperFakeContext` -> `_MocketSSLContext`
reason being: align with class-naming in python stdlib to make it more obvious what is being mocked.
=> Refactor rename ssl classes

.github/workflows/main.yml, mocket/inject.py, mocket/mocket.py, mocket/recording.py, mocket/socket.py, mocket/utils.py
as discussed here an implementation for a dedicated request-recorder class.
=> Refactor introduce recording storage

Makefile, tests/test_mocket.py, tests/test_redis.py
It used to be possible to only run the tests relying on Mocket - non-real `socket` ones - but it looks like something changed in the Redis client that is worth investigating (something more needs to be mocked).
It helps to overcome issues like the one mentioned in #272
See https://redis.io/docs/latest/commands/client-setinfo/
=> Target `make safetest` got broken

mocket/__init__.py, mocket/decorators/async_mocket.py, mocket/decorators/mocketizer.py, mocket/utils.py, pyproject.toml
=> Missing dependency

.github/workflows/main.yml
See https://docs.astral.sh/uv/guides/integration/github/#caching
=> Fix for caching when using `uv`

mocket/socket.py
Closes: #287
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
=> Fix test_truesendall failure on MacOS

mocket/mocket.py, mocket/mocks/mockhttp.py, mocket/plugins/httpretty/__init__.py, mocket/utils.py, pyproject.toml, tests/test_mocket_utils.py
See #203 
While the type hints introduced are not that extensive, they do pass some basic mypy rules (e.g., [disallow_untyped_decorators](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_decorators)).
I used `tests.test_httpretty` to test the type hints introduced. Again, while it's not an exhaustive approach, it provides some sanity check that types work as expected.
=> Add type hints to mocket.plugins.httpretty

mocket/plugins/httpretty/__init__.py
I'm migrating a large codebase with lots of http mocking from httpretty to python-mocket and making heavy use of your httpretty plugin – many thanks for making this and for actively maintaining python-mocket! ❤️ It is much appreciated!
This PR makes sure match_querystring is passed along properly to ~Entry` when multiple responses are registered using the httpretty plugin.  `match_querystring` is already passed along as expected when a single response is registered, but not currently when multiple responses are registered. 
This change makes a bunch of my tests pass, that otherwise would not
=> Match querystring for multiple responses in httpretty plugin

mocket/mode.py, mocket/socket.py, tests/test_mode.py
This is another change on the back of #295 – I made this locally and it helped quite a bit as i was migrating from httpretty to mocket. This way you can see which url the test tried to access, but couldn't.
Was specifically quite helpful in figuring out the querystring issue. Example output:
```
mocket.exceptions.StrictMocketException: Mocket tried to use the real `socket` module while STRICT mode was active.
Attempted address: slack.com:443
First request line: GET /api/users.list?team_id=T_e2e_correctly_calculates_enterprise1&limit=500 HTTP/1.1
Registered entries:
('slack.com', 443):
Entry(method='GET', schema='https', location=('slack.com', 443), path='/api/users.list', query='')
```
Feel free to edit the code or make a separate PR if there's a better way to do this. I think the code …
=> Output attempted address in strict mode

README.rst, mocket/__init__.py, mocket/mocks/mockhttp.py, mocket/plugins/httpretty/__init__.py, tests/test_http.py, tests/test_https.py, tests/test_httpx.py
=> Define an alternative `can_handle` logic by passing a callable
